# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - libopengl-dev # So the various OpenGL libraries can be imported properly

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
  builder: dirhtml # Each module gets its own directory with a single index.html; makes for nicer URLs

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - opengl-window