[project]
name = "libretro.py"
dynamic = ["version"]
description = "A libretro frontend for Python intended for testing cores."
readme = "README.md"
requires-python = ">=3.11"
license = {text = "MIT License"}
authors = [
    {name = "Jesse Talavera", email = "jesse@jesse.tg"},
]
maintainers = [
    {name = "Jesse Talavera", email = "jesse@jesse.tg"},
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Environment :: Console :: Framebuffer",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: C",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Games/Entertainment",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Testing",
]
keywords = ["libretro", "retroarch", "emulation", "testing", "retrogaming"]

[project.urls]
Homepage = "https://github.com/JesseTG/libretro.py"
Issues = "https://github.com/JesseTG/libretro.py/issues"
Repository = "https://github.com/JesseTG/libretro.py"
Changelog = "https://github.com/JesseTG/libretro.py/blob/master/CHANGELOG.md"

[build-system]
requires = [
    'bandit == 1.7.*',
    'black == 23.*',
    'build == 0.10.*',
    'flake8 == 6.*',
    'isort == 5.*',
    'mypy == 1.5.*',
    'pytest == 7.*',
    'pytest-cov == 4.*',
    'setuptools>=69.1.1',
    'twine == 4.*',
]
build-backend = "setuptools.build_meta"

[tool.black]
preview = true
line-length = 120
skip-string-normalization = true

[tool.isort]
profile = "black"
